src/objects/ElapsedRevenue__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityProrate__c</fullName>
        <label>商談按分</label>
        <referenceTo>OpportunityProrate__c</referenceTo>
        <relationshipLabel>経過収益</relationshipLabel>
        <relationshipName>ElapsedRevenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProgressMonth__c</fullName>
        <description>Triggerによりレコード作成時に連番を代入。</description>
        <inlineHelpText>経過収益の０：ゼロから始まる連番。</inlineHelpText>
        <label>進捗月数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>経過収益</label>
    <nameField>
        <displayFormat>経過収益-{0000}</displayFormat>
        <label>経過収益名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Prorating__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggerでレコード更新時の処理起動の判定に使用。</description>
        <inlineHelpText>チェックONで、経過収益を作成。
チェックOFFで、経過収益を削除。</inlineHelpText>
        <label>按分実行</label>
        <type>Checkbox</type>
    </fields>
    <label>商談</label>
    <nameField>
        <displayFormat>商談-{0000}</displayFormat>
        <label>商談名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品</label>
        <referenceTo>Product2__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>商談商品</label>
    <nameField>
        <displayFormat>商談商品-{0000}</displayFormat>
        <label>商談商品名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityProrate__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityLineItem__c</fullName>
        <label>商談商品</label>
        <referenceTo>OpportunityLineItem__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SplitTimes__c</fullName>
        <description>入力済の商品の按分回数を優先で出力。
按分開始日と按分終了日の日数を３１で除算し整数に丸めた結果。</description>
        <formula>IF ( NOT( ISBLANK( Prorate__r.Product2__r.SplitTimes__c ) ) , 

 Prorate__r.Product2__r.SplitTimes__c
 , 
 ROUND( ( SplitEndDateFixed__c - SplitStartDateFixed__c ) / 31 , 0 )

)</formula>
        <inlineHelpText>商品の按分回数か、商品の按分回数が空白の場合は、按分開始日と按分終了日の間の月数。</inlineHelpText>
        <label>按分回数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商談按分</label>
    <nameField>
        <displayFormat>商談按分-{0000}</displayFormat>
        <label>商談按分名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2__c.object
<CustomObject>
    <fields>
        <fullName>SplitTimes__c</fullName>
        <description>按分の按分回数の数式内で参照。</description>
        <inlineHelpText>按分の按分終了月を無視し、固定の按分回数を指定する場合に記入。</inlineHelpText>
        <label>按分回数</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityLogic.cls
public class OpportunityLogic {

    public static void CreateElapsedRevenue(List<Opportunity__c> opList){
        System.debug('@@@ CreateElapsedRevenue()');
        Set<Id> opIdSet = new Set<Id>();
        for(Opportunity__c op :opList){
            opIdSet.add(op.Id);
        }
        List<OpportunityProrate__c> opProrateWithElapsedRevenuesList = [SELECT Id, SplitTimes__c, Opportunity__c, (SELECT Id FROM ElapsedRevenues__r) FROM OpportunityProrate__c  WHERE Opportunity__c = :opIdSet];
        Set<Id> existErIdSet = new Set<Id>();
        List<ElapsedRevenue__c> erList = new List<ElapsedRevenue__c>();
        Set<Id> cancelOpIdSet = new Set<Id>();
        for(Opportunity__c op :opList){
            if(op.Prorating__c){
                for(OpportunityProrate__c opp :opProrateWithElapsedRevenuesList){
                    if(op.Id == opp.Opportunity__c){
                        System.debug('***opp ' + opp);
                        for (Integer i=0;i<=opp.SplitTimes__c;i++) {
                            ElapsedRevenue__c er = new ElapsedRevenue__c();
                            er.OpportunityProrate__c = opp.Id;
                            er.ProgressMonth__c = i;
                            erList.add(er);
                            System.debug('***er ' + er);
                        }
                    }
                }
            }else{
                for(OpportunityProrate__c opp :opProrateWithElapsedRevenuesList){
                    if(op.Id == opp.Opportunity__c){
                        System.debug('***opp ' + opp);
                        for(ElapsedRevenue__c existEr :opp.ElapsedRevenues__r){
                            System.debug('***existEr ' + existEr);
                            existErIdSet.add(existEr.Id);
                        }
                    }
                }
                cancelOpIdSet.add(op.Id);
            }
        }
        delete [SELECT Id FROM ElapsedRevenue__c WHERE Id = :existErIdSet];
        insert erList;
        List<OpportunityLineItem__c> opliList = [SELECT Id, Opportunity__c, Product2__c FROM OpportunityLineItem__c WHERE Opportunity__c = :cancelOpIdSet];
        if(opliList.size() > 0){
            OpportunityLineItemLogic.CreateOpportunityProrate(opliList);
        }
    }

}