src/objects/ElapsedRevenue__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityProrate__c</fullName>
        <label>商談按分</label>
        <referenceTo>OpportunityProrate__c</referenceTo>
        <relationshipLabel>経過収益</relationshipLabel>
        <relationshipName>ElapsedRevenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>経過収益</label>
    <nameField>
        <displayFormat>経過収益-{0000}</displayFormat>
        <label>経過収益名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>属性</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OpportunityAttribute</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>完了予定日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prorating__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggerでレコード更新時の処理起動の判定に使用。</description>
        <inlineHelpText>チェックONで、経過収益を作成。
チェックOFFで、経過収益を削除。</inlineHelpText>
        <label>按分実行</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SalesPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>担当営業</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>商談</label>
    <nameField>
        <displayFormat>商談-{0000}</displayFormat>
        <label>商談名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品</label>
        <referenceTo>Product2__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>合計金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>商談商品</label>
    <nameField>
        <displayFormat>商談商品-{0000}</displayFormat>
        <label>商談商品名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityProrate__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityLineItem__c</fullName>
        <label>商談商品</label>
        <referenceTo>OpportunityLineItem__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prorate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>按分</label>
        <referenceTo>Prorate__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>商談按分</label>
    <nameField>
        <displayFormat>商談按分-{0000}</displayFormat>
        <label>商談按分名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2__c.object
<CustomObject>
    <fields>
        <fullName>ServiceType__c</fullName>
        <label>サービス種別</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceYears__c</fullName>
        <label>サービス対象年数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prorate__c.object
<CustomObject>
    <fields>
        <fullName>AmountRatio__c</fullName>
        <inlineHelpText>商談商品を複数の期間と金額で按分する場合の金額を算出する元になる割合（パーセント）。</inlineHelpText>
        <label>金額割合</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品</label>
        <referenceTo>Product2__c</referenceTo>
        <relationshipLabel>按分</relationshipLabel>
        <relationshipName>Prorates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SplitEndMonth__c</fullName>
        <defaultValue>3</defaultValue>
        <inlineHelpText>按分終了日を算出する元になる月。
１～１２までの整数が入力必須。</inlineHelpText>
        <label>按分終了月</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SplitYears__c</fullName>
        <inlineHelpText>按分回数を算出する元になる年数。
整数必須。</inlineHelpText>
        <label>按分年数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>按分</label>
    <nameField>
        <displayFormat>按分-{0000}</displayFormat>
        <label>按分名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>地域</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/InstallationTests.cls
@isTest
private class InstallationTests {

    @testSetup
    static void setup() {
        createMasterDatas(10,5);
    }

    @isTest
    static void InstallTest010() {
        System.debug('###InstallTest010');
        //OpportunityLineItemTrigger & OpportunityLineItemLogic
        createOpportunityDatas(10, -365, 21);
        Test.startTest();
        createOpportunityLineItemDatas(99);
        Test.stopTest();
    }

    @isTest
    static void InstallTest011() {
        System.debug('###InstallTest011');
        //OpportunityLineItemTrigger & OpportunityLineItemLogic
        createOpportunityDatas(10, -365, 21);
        createOpportunityLineItemDatas(99);
        List<OpportunityLineItem__c> opliList = [SELECT Id, Product2__c FROM OpportunityLineItem__c];
        for(OpportunityLineItem__c opli : opliList){
            opli.TotalPrice__c	 = 999;
        }
        Test.startTest();
        update opliList;
        Test.stopTest();
    }

    @isTest
    static void InstallTest020() {
        System.debug('###InstallTest020');
        //OpportunityTrigger & OpportunityLogic
        createOpportunityDatas(10, -365, 21);
        createOpportunityLineItemDatas(99);
        List<Opportunity__c> opList = [SELECT Id FROM Opportunity__c];
        for(Opportunity__c op : opList){
            op.Prorating__c = true;
        }
        Test.startTest();
        update opList;
        Test.stopTest();
    }

    @isTest
    static void InstallTest021() {
        System.debug('###InstallTest021');
        //OpportunityTrigger & OpportunityLogic
        createOpportunityDatas(1, -365, 365);
        createOpportunityLineItemDatas(99);
        List<Opportunity__c> opList = [SELECT Id FROM Opportunity__c];
        for(Opportunity__c op : opList){
            op.CloseDate__c = System.today();
        }
        Test.startTest();
        update opList;
        Test.stopTest();
    }

    @isTest
    static void InstallTest022() {
        System.debug('###InstallTest022');
        //OpportunityTrigger & OpportunityLogic
        createOpportunityDatas(1, -365, 150);
        createOpportunityLineItemDatas(1);
        List<Opportunity__c> opList = [SELECT Id FROM Opportunity__c];
        opList[0].Prorating__c = true;
        update opList[0];
        opList[0].Prorating__c = false;
        Test.startTest();
        update opList[0];
        Test.stopTest();
    }

    @isTest
    static void InstallTest023() {
        System.debug('###InstallTest023');
        //OpportunityTrigger & OpportunityLogic
        createOpportunityDatas(1, -365, 150);
        createOpportunityLineItemDatas(1);
        List<Opportunity__c> opList = [SELECT Id FROM Opportunity__c];
        List<OpportunityProrate__c> oppList = [SELECT Id FROM OpportunityProrate__c];
        ElapsedRevenue__c er = new ElapsedRevenue__c();
        er.OpportunityProrate__c = oppList[0].Id;
        insert er;
        opList[0].Prorating__c = true;
        Test.startTest();
        update opList[0];
        Test.stopTest();
    }

    static void createMasterDatas(Integer numAcc, Integer numPr){
        System.debug('###createMasterDatas');
        // Setup Testing Datas

        Profile testProfile = [SELECT Id FROM Profile WHERE Name LIKE '%カスタム Platform ユーザ%']; 
        User testUser01 = new User (Alias = 'rdok3801', Email='rand.okuda+38@gmail.com', LastName='randokuda01', ProfileId = testProfile.Id, LocaleSidKey='ja_JP', LanguageLocaleKey='ja', EmailEncodingKey='ISO-2022-JP', TimeZoneSidKey='Asia/Tokyo', UserName='rand.okuda.201711131221.01@gmail.com');
        insert testUser01;
        User testUser02 = new User (Alias = 'rdok3802', Email='rand.okuda+38@gmail.com', LastName='randokuda02', ProfileId = testProfile.Id, LocaleSidKey='ja_JP', LanguageLocaleKey='ja', EmailEncodingKey='ISO-2022-JP', TimeZoneSidKey='Asia/Tokyo', UserName='rand.okuda.201711131221.02@gmail.com');
        insert testUser02;

        List<Account> accList = new List<Account>();
        for (Integer i=0;i<numAcc;i++) {
            Account acc = new Account();
            acc.Name = 'ACC-' + i;
            System.debug('###acc ' + acc);
            accList.add(acc);
        }
        insert accList;
        
        List<String> ServiceTypeList = new List<String>();
        Schema.DescribeFieldResult serviceTypeListFidldResult = Product2__c.ServiceType__c.getDescribe();
        List<Schema.PicklistEntry> serviceTypeListPicklistEntrys = serviceTypeListFidldResult.getPicklistValues();
        Integer numStp = serviceTypeListPicklistEntrys.size() - 1;
        for (Schema.PicklistEntry serviceTypeListPicklistEntry : serviceTypeListPicklistEntrys) {
            System.debug('###serviceTypeListPicklistEntry ' + serviceTypeListPicklistEntry);
            if(serviceTypeListPicklistEntry.isActive()){
                ServiceTypeList.add(String.valueOf(serviceTypeListPicklistEntry.getValue()));
            }
        }
        List<Product2__c> pdList = new List<Product2__c>();
        Integer j = 0;
        for (Integer i=0;i<numPr;i++) {
            Product2__c pd = new Product2__c();
            pd.Name = 'PD-' + i;
            pd.ServiceType__c = ServiceTypeList[j];
            pd.ServiceYears__c = 1;
            pdList.add(pd);
            System.debug('###pd ' + pd);
            if(j == numStp){
                j = 0;
            }else{
                j++;
            }
        }
        insert pdList;

        List<Prorate__c> prList = new  List<Prorate__c>();
        Integer splitEndMonthNum = 1;
        for (Product2__c pd : pdList){
            Prorate__c pr = new Prorate__c();
            if (splitEndMonthNum > 12){
                splitEndMonthNum = 1;
            }
            pr.SplitEndMonth__c = splitEndMonthNum;
            pr.SplitYears__c = 1;
            pr.Product2__c = pd.Id;
            pr.AmountRatio__c = 100;
            prList.add(pr);
            System.debug('###pr ' + pr);
            splitEndMonthNum ++;
        }
        insert prList;

    }

    static void createOpportunityDatas(Integer numOpp, Integer numDay, Integer numSpan){
        System.debug('###createOpportunityDatas');
        // Setup Testing Datas

        List<Account> aList = [SELECT Id FROM Account];
        List<User> uList = [SELECT Id, Region__c FROM User WHERE Region__c != null];
        List<Opportunity__c> opList = new List<Opportunity__c>();
        for(Account a :aList){
            if(numOpp == 0){
                break;
            }
            for (Integer i=0;i<=2;i++) {
                if(numOpp == 0){
                    break;
                }
                for(User u :uList){
                    Opportunity__c op = new Opportunity__c();
                    op.Account__c = a.Id;
                    op.SalesPerson__c = u.Id;
                    op.Attribute__c = '3';
                    op.CloseDate__c = System.today().addDays(numDay);
                    opList.add(op);
                    System.debug('###op ' + op);
                    numDay = numDay + numSpan;
                    numOpp -= 1;
                    if(numOpp == 0){
                        break;
                    }
                }
            }
        }
        insert opList;

    }

    static void createOpportunityLineItemDatas(Integer numSp){
        System.debug('###createOpportunityLineItemDatas');
        // Setup Testing Datas

        List<Opportunity__c> opList = [SELECT Id FROM Opportunity__c];
        List<Product2__c> pdList = [SELECT Id FROM Product2__c];
        List<OpportunityLineItem__c> opliList = new List<OpportunityLineItem__c>();
        Integer numPd = 0;
        for(Opportunity__c op :opList){
            for (Integer i=0;i<=1;i++) {
                OpportunityLineItem__c opli = new OpportunityLineItem__c();
                opli.Product2__c = pdList[numPd].Id;
                opli.Opportunity__c = op.Id;
                if(opliList.size() <= numSp){
                    opliList.add(opli);
                    System.debug('###opli ' + opli);
                }
                if(numPd == pdList.size()-1){
                    numPd = 0;
                }else{
                    numPd ++;
                }
            }
        }
        insert opliList;

    }

}