src/objects/Opportunity__c.object
<CustomObject>
    <label>商談</label>
    <nameField>
        <displayFormat>商談-{0000}</displayFormat>
        <label>商談名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品</label>
        <referenceTo>Product2__c</referenceTo>
        <relationshipLabel>商談商品</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>商談商品</label>
    <nameField>
        <displayFormat>商談商品-{0000}</displayFormat>
        <label>商談商品名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityProrate__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityLineItem__c</fullName>
        <label>商談商品</label>
        <referenceTo>OpportunityLineItem__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商談</label>
        <referenceTo>Opportunity__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prorate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>按分</label>
        <referenceTo>Prorate__c</referenceTo>
        <relationshipLabel>商談按分</relationshipLabel>
        <relationshipName>OpportunityProrates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>商談按分</label>
    <nameField>
        <displayFormat>商談按分-{0000}</displayFormat>
        <label>商談按分名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2__c.object
<CustomObject>
    <label>商品</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prorate__c.object
<CustomObject>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>商品</label>
        <referenceTo>Product2__c</referenceTo>
        <relationshipLabel>按分</relationshipLabel>
        <relationshipName>Prorates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>按分</label>
    <nameField>
        <displayFormat>按分-{0000}</displayFormat>
        <label>按分名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemLogic.cls
public class OpportunityLineItemLogic {

    public static void CreateOpportunityProrate(List<OpportunityLineItem__c> opliList){
        System.debug('@@@ CreateOpportunityProrate()');
        Set<Id> pdIdSet = new Set<Id>();
        for(OpportunityLineItem__c opliL :opliList){
            pdIdSet.add(opliL.Product2__c);
        }
        Set<Id> opliIdSet = new Set<Id>();
        for(OpportunityLineItem__c opli :opliList){
            opliIdSet.add(opli.Id);
        }
        Set<Id> existOppIdSet = new Set<Id>();
        for(OpportunityProrate__c opp : [SELECT Id, OpportunityLineItem__c FROM OpportunityProrate__c WHERE OpportunityLineItem__c = :opliIdSet]){
            existOppIdSet.add(opp.Id);
        }
        List<Product2__c> pdListWithProrate = [SELECT Id, (SELECT Id FROM Prorates__r) FROM Product2__c WHERE Id = :pdIdSet];
        List<OpportunityProrate__c> opPrList = new List<OpportunityProrate__c>();
        for(OpportunityLineItem__c opli :opliList){
            for(Product2__c pd :pdListWithProrate){
                if(opli.Product2__c == pd.Id){
                    for(Prorate__c pr :pd.Prorates__r){
                        OpportunityProrate__c opPr = new OpportunityProrate__c();
                        opPr.Opportunity__c = opli.Opportunity__c;
                        opPr.Prorate__c = pr.Id;
                        opPr.OpportunityLineItem__c = opli.Id;
                        opPrList.add(opPr);
                        System.debug('***opPr ' + opPr);
                    }
                    break;
                }
            }
        }
        delete [SELECT Id FROM OpportunityProrate__c WHERE Id = :existOppIdSet];
        insert opPrList;
    }

}